Pandas

In [ ]:
import pandas as pd

data = {
    'Data Point': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'Value': [5, 8, 12, 15, 21, 24, 29, 33, 38, 42]
}

df = pd.DataFrame(data)


In [ ]:
df

Data Point  Value
0          A      5
1          B      8
2          C     12
3          D     15
4          E     21
5          F     24
6          G     29
7          H     33
8          I     38
9          J     42

In [ ]:
df.describe()

Value
count  10.000000
mean   22.700000
std    12.737085
min     5.000000
25%    12.750000
50%    22.500000
75%    32.000000
max    42.000000

In [ ]:
df['Value'].var()

162.23333333333332

In [ ]:
df['Value'].sum()

227

In [ ]:
df['Value']**0.5

0    2.236068
1    2.828427
2    3.464102
3    3.872983
4    4.582576
5    4.898979
6    5.385165
7    5.744563
8    6.164414
9    6.480741
Name: Value, dtype: float64

In [ ]:
df['Value']**2

0      25
1      64
2     144
3     225
4     441
5     576
6     841
7    1089
8    1444
9    1764
Name: Value, dtype: int64

In [ ]:
df

Data Point  Value
0          A      5
1          B      8
2          C     12
3          D     15
4          E     21
5          F     24
6          G     29
7          H     33
8          I     38
9          J     42

In [ ]:
 df[df['Value'] > 20]

Data Point  Value
4          E     21
5          F     24
6          G     29
7          H     33
8          I     38
9          J     42

In [ ]:
df.sort_values(by='Value', ascending=False)

Data Point  Value
9          J     42
8          I     38
7          H     33
6          G     29
5          F     24
4          E     21
3          D     15
2          C     12
1          B      8
0          A      5

In [ ]:
df.sort_values(by='Value', ascending=True)

Data Point  Value
0          A      5
1          B      8
2          C     12
3          D     15
4          E     21
5          F     24
6          G     29
7          H     33
8          I     38
9          J     42

In [ ]:
df.rename(columns={'Data Point': 'Label', 'Value': 'Original Value'})

Label  Original Value
0     A               5
1     B               8
2     C              12
3     D              15
4     E              21
5     F              24
6     G              29
7     H              33
8     I              38
9     J              42

In [ ]:
df.nlargest(3, 'Value')

Data Point  Value
9          J     42
8          I     38
7          H     33

In [ ]:
df.nsmallest(3, 'Value')

Data Point  Value
0          A      5
1          B      8
2          C     12

In [ ]:
df.to_csv('data_points.csv', index=False)

In [ ]:
df['Value'].nunique()

10

In [ ]:
df['Value'].value_counts()

5     1
8     1
12    1
15    1
21    1
24    1
29    1
33    1
38    1
42    1
Name: Value, dtype: int64

In [ ]:
df['Value'].cumsum()

0      5
1     13
2     25
3     40
4     61
5     85
6    114
7    147
8    185
9    227
Name: Value, dtype: int64

In [ ]:
df['Category'] = df['Value'].apply(lambda x: 'Low' if x < 20 else 'High')

In [ ]:
df

Data Point  Value Category
0          A      5      Low
1          B      8      Low
2          C     12      Low
3          D     15      Low
4          E     21     High
5          F     24     High
6          G     29     High
7          H     33     High
8          I     38     High
9          J     42     High

In [ ]:
df['Value'] + 10

0    15
1    18
2    22
3    25
4    31
5    34
6    39
7    43
8    48
9    52
Name: Value, dtype: int64

In [ ]:
df[(df['Value'] > 20) & (df['Value'] % 2 == 0)]


Data Point  Value Category
5          F     24     High
8          I     38     High
9          J     42     High

In [ ]:
df.groupby('Category')['Value'].count()

Category
High    6
Low     4
Name: Value, dtype: int64

In [ ]:
df.groupby('Category')['Value'].mean()

Category
High    31.166667
Low     10.000000
Name: Value, dtype: float64

In [ ]:
df.groupby('Category')['Value'].sum()

Category
High    187
Low      40
Name: Value, dtype: int64

In [ ]:
df.pivot_table(index='Category', columns='Data Point', values='Value', aggfunc='mean')

Data Point    A    B     C     D     E     F     G     H     I     J
Category                                                            
High        NaN  NaN   NaN   NaN  21.0  24.0  29.0  33.0  38.0  42.0
Low         5.0  8.0  12.0  15.0   NaN   NaN   NaN   NaN   NaN   NaN

In [ ]:
df.stack()

0  Data Point       A
   Value            5
   Category       Low
1  Data Point       B
   Value            8
   Category       Low
2  Data Point       C
   Value           12
   Category       Low
3  Data Point       D
   Value           15
   Category       Low
4  Data Point       E
   Value           21
   Category      High
5  Data Point       F
   Value           24
   Category      High
6  Data Point       G
   Value           29
   Category      High
7  Data Point       H
   Value           33
   Category      High
8  Data Point       I
   Value           38
   Category      High
9  Data Point       J
   Value           42
   Category      High
dtype: object

In [ ]:
# Replace missing values with a specific value (e.g., 0)
df.fillna(0, inplace=True)

# Drop rows with missing values
df.dropna(inplace=True)


In [ ]:
df['Category'].str.lower()

0     low
1     low
2     low
3     low
4    high
5    high
6    high
7    high
8    high
9    high
Name: Category, dtype: object

In [ ]:
df['Total'] = df.apply(lambda row: row['Value'] + 1, axis=1)

In [ ]:
df.drop(columns=['Category'], inplace=True)


In [ ]:
df

Data Point  Value  Total
0          A      5      6
1          B      8      9
2          C     12     13
3          D     15     16
4          E     21     22
5          F     24     25
6          G     29     30
7          H     33     34
8          I     38     39
9          J     42     43

In [ ]:
df.stack()

0  Data Point     A
   Value          5
1  Data Point     B
   Value          8
2  Data Point     C
   Value         12
3  Data Point     D
   Value         15
4  Data Point     E
   Value         21
5  Data Point     F
   Value         24
6  Data Point     G
   Value         29
7  Data Point     H
   Value         33
8  Data Point     I
   Value         38
9  Data Point     J
   Value         42
dtype: object

In [ ]:
# Calculate the rank of the 'Value' column and store it in a new column 'Rank'
df['Rank'] = df['Value'].rank(ascending=True, method='average')


In [ ]:
df

Data Point  Value  Total  Rank
0          A      5      6   1.0
1          B      8      9   2.0
2          C     12     13   3.0
3          D     15     16   4.0
4          E     21     22   5.0
5          F     24     25   6.0
6          G     29     30   7.0
7          H     33     34   8.0
8          I     38     39   9.0
9          J     42     43  10.0

In [ ]:
df['Value Diff'] = df['Value'] - df['Value'].shift(1)



In [ ]:
df

Data Point  Value  Total  Rank  Value Diff
0          A      5      6   1.0         NaN
1          B      8      9   2.0         3.0
2          C     12     13   3.0         4.0
3          D     15     16   4.0         3.0
4          E     21     22   5.0         6.0
5          F     24     25   6.0         3.0
6          G     29     30   7.0         5.0
7          H     33     34   8.0         4.0
8          I     38     39   9.0         5.0
9          J     42     43  10.0         4.0

In [ ]:
df.drop(3)


Data Point  Value  Total  Rank  Value Diff
0          A      5      6   1.0         NaN
1          B      8      9   2.0         3.0
2          C     12     13   3.0         4.0
4          E     21     22   5.0         6.0
5          F     24     25   6.0         3.0
6          G     29     30   7.0         5.0
7          H     33     34   8.0         4.0
8          I     38     39   9.0         5.0
9          J     42     43  10.0         4.0

In [ ]:
df.groupby(['Category', 'Data Point'])['Value'].sum()



Category  Data Point
High      E             21
          F             24
          G             29
          H             33
          I             38
          J             42
Low       A              5
          B              8
          C             12
          D             15
Name: Value, dtype: int64

In [ ]:
df

Data Point  Value  Total  Rank  Value Diff  Category_High  Category_Low  \
0          A      5      6   1.0         NaN              0             1   
1          B      8      9   2.0         3.0              0             1   
2          C     12     13   3.0         4.0              0             1   
3          D     15     16   4.0         3.0              0             1   
4          E     21     22   5.0         6.0              1             0   
5          F     24     25   6.0         3.0              1             0   
6          G     29     30   7.0         5.0              1             0   
7          H     33     34   8.0         4.0              1             0   
8          I     38     39   9.0         5.0              1             0   
9          J     42     43  10.0         4.0              1             0   

  Category  
0      Low  
1      Low  
2      Low  
3      Low  
4     High  
5     High  
6     High  
7     High  
8     High  
9     High

numpy



In [ ]:
import numpy as np

data = [5, 8, 12, 15, 21, 24, 29, 33, 38, 42]
np_array = np.array(data)


In [ ]:
np.sum(np_array)

227

In [ ]:
np.mean(np_array)

22.7

In [ ]:
np.std(np_array)

12.083459769453448

In [ ]:
np.min(np_array)

5

In [ ]:
np.max(np_array)

42

In [ ]:
np_array[3]

15

In [ ]:
np_array[2:5]

array([12, 15, 21])

In [ ]:
np_array.reshape(2, 5)

array([[ 5,  8, 12, 15, 21],
       [24, 29, 33, 38, 42]])

In [ ]:
 np_array * 2

array([10, 16, 24, 30, 42, 48, 58, 66, 76, 84])

In [ ]:
np.argmax(np_array)


9

In [ ]:
np.argmin(np_array)


0

In [ ]:
np.sort(np_array)

array([ 5,  8, 12, 15, 21, 24, 29, 33, 38, 42])

In [ ]:
condition = np_array > 20
np_array[condition]

array([21, 24, 29, 33, 38, 42])

In [ ]:
np.sqrt(np_array)

array([2.23606798, 2.82842712, 3.46410162, 3.87298335, 4.58257569,
       4.89897949, 5.38516481, 5.74456265, 6.164414  , 6.4807407 ])

In [ ]:
np.exp(np_array)

array([1.48413159e+02, 2.98095799e+03, 1.62754791e+05, 3.26901737e+06,
       1.31881573e+09, 2.64891221e+10, 3.93133430e+12, 2.14643580e+14,
       3.18559318e+16, 1.73927494e+18])

In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
np.dot(vector1, vector2)


32

In [ ]:
array1 = np.array([1, 2, 3])
scalar = 2
array1 * scalar


array([2, 4, 6])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
np.concatenate((array1, array2))


array([1, 2, 3, 4, 5, 6])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([2, 2, 3])
array1 == array2


array([False,  True,  True])

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
np.matmul(matrix1, matrix2)


array([[19, 22],
       [43, 50]])

In [ ]:
values = np.array([1, 10, 100])
np.log(values)


array([0.        , 2.30258509, 4.60517019])

In [ ]:
np.log10(values)

array([0., 1., 2.])

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
np.transpose(matrix)

array([[1, 3],
       [2, 4]])

In [ ]:
np.arange(0, 10, 2)  # Start, stop, step


array([0, 2, 4, 6, 8])

In [ ]:
 np.linspace(0, 1, 5)  # Start, stop, number of values


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.logspace(0, 2, 5)  # 10^start, 10^stop, number of values


array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])